import os
import time
import pyautogui
import requests
from bs4 import BeautifulSoup
from automation.system_control import SystemControl
from automation.browser_control import BrowserControl

class ActionExecutor:
    """
    Executes the tasks generated by GPT breakdown.
    """
    
    def __init__(self, speaker):
        self.speaker = speaker
        self.system_control = SystemControl()
        self.browser_control = BrowserControl()
        
    def execute_tasks(self, tasks):
        """
        Execute a list of tasks sequentially.
        
        Args:
            tasks (list): List of task strings to execute
        """
        for task in tasks:
            try:
                self._execute_single_task(task)
                time.sleep(1)  # Brief pause between tasks
            except Exception as e:
                self.speaker.speak(f"Error executing task: {str(e)}")
                
    def _execute_single_task(self, task):
        """
        Execute a single task based on its action type.
        
        Args:
            task (str): Task string in format "action: content"
        """
        if ":" not in task:
            return
            
        action, content = task.split(":", 1)
        action = action.strip().lower()
        content = content.strip()
        
        if action == "say":
            self.speaker.speak(content)
            
        elif action == "search":
            result = self._search_internet(content)
            self.speaker.speak(result)
            
        elif action == "open":
            self.system_control.open_application(content)
            time.sleep(2)  # Wait for app to open
            
        elif action == "type":
            self._type_text(content)
            
        elif action == "save_file":
            self._save_file(content)
            
        elif action == "close":
            self._close_application(content)
            
    def _search_internet(self, query):
        """
        Search the internet and return a brief result.
        
        Args:
            query (str): Search query
            
        Returns:
            str: Search result summary
        """
        try:
            # Use DuckDuckGo instant answer API for quick results
            url = f"https://api.duckduckgo.com/?q={query}&format=json&no_html=1&skip_disambig=1"
            response = requests.get(url, timeout=5)
            data = response.json()
            
            # Try to get instant answer
            if data.get('AbstractText'):
                return data['AbstractText'][:200] + "..."
            elif data.get('Answer'):
                return data['Answer']
            elif data.get('RelatedTopics') and len(data['RelatedTopics']) > 0:
                return data['RelatedTopics'][0].get('Text', 'No specific answer found')[:200] + "..."
            else:
                # Fallback: open Google search
                self.browser_control.search_google(query)
                return f"I've opened a Google search for {query}"
                
        except Exception as e:
            # Fallback: open Google search
            self.browser_control.search_google(query)
            return f"I've opened a Google search for {query}"
    
    def _type_text(self, text):
        """
        Type text into the currently active application.
        
        Args:
            text (str): Text to type
        """
        try:
            pyautogui.write(text)
        except Exception as e:
            self.speaker.speak(f"Could not type text: {str(e)}")
    
    def _save_file(self, filename=None):
        """
        Save the current file using Ctrl+S.
        
        Args:
            filename (str, optional): Filename to save as
        """
        try:
            pyautogui.hotkey('ctrl', 's')
            time.sleep(1)
            
            if filename:
                pyautogui.write(filename)
                pyautogui.press('enter')
                
        except Exception as e:
            self.speaker.speak(f"Could not save file: {str(e)}")
    
    def _close_application(self, app_name):
        """
        Close an application using Alt+F4.
        
        Args:
            app_name (str): Name of application to close
        """
        try:
            pyautogui.hotkey('alt', 'f4')
        except Exception as e:
            self.speaker.speak(f"Could not close {app_name}: {str(e)}")